inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.2
  Include:
    - Gemfile
    - jekyll-theme-poole.spec
    - Rakefile

  Exclude:
    - .rubocop.yml
    - .gitignore
    - Gemfile.lock
    - LICENSE.md
    - vendor/**/*
