language: ruby
rvm:
  - 2.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - bundle install

script:
  - bundle exec jekyll build --drafts
  - bundle exec htmlproof ./_site

notifications:
  email: false

branches:
  only:
    - gh-pages
